### ISSUE TITLE
Handling DOMStateStorage failures

### ISSUE THREAD

**Issue by mjackson** [mjackson/history#123]
Currently, we just warn when calls to `DOMStateStorage`'s `saveState` and `readState` fail. However, warnings don't really seem right here since the app will be broken.

One idea I had is that we could possibly [fallback to using `window.name` for session storage](http://www.thomasfrank.se/sessionvars.html) instead of `window.sessionStorage`. The main limitations here would be:

- possible conflicts with other libraries using `window.name`. This is highly unlikely since `window.name` is a really obscure API, but we'll definitely want to put a caveat in the docs so people at least know about it.
- size. It looks like we're limited to 2MB.

Thoughts?

Edit: This is a follow-up to #120

**Comment by kentcdodds** [comment]
FWIW (probably not much), the angular project uses `window.name` as a place to store some debugging related state ([defer bootstrap](https://docs.angularjs.org/guide/bootstrap#deferred-bootstrap) and [debug info](https://github.com/angular/angular.js/blob/17715fa3668b1fcabaedcd82e2e57b2a80e0a0c2/src/Angular.js#L1652-L1655)).

**Comment by mjackson** [comment]
Whoa, great catch @kentcdodds. Thanks for pointing that out. Can you help me understand how people use that? Is it mainly for dev?

**Comment by kentcdodds** [comment]
Pretty much soley for dev

**Comment by kentcdodds** [comment]
Basically, for perf, angular has the ability to disable dev related info. Useful for production deploys. But when you need to debug a production app, having that debug info is helpful. But you need a full page refresh to turn it on. So to store state across the page reload, angular uses window.name.

**Comment by mjackson** [comment]
Gonna close this until one of us finds time to work on it.
