### ISSUE TITLE
Make relative transition paths work

### ISSUE THREAD

**Issue by saikat** [mjackson/history#135]
I saw the issue here https://github.com/rackt/react-router/issues/1828 and it was closed to continue discussion in this repo. Apologies if this is a dupe or has already been implemented, but I could not find it anywhere.

**Comment by taion** [comment]
Thanks!

Note that this is slightly different from https://github.com/rackt/react-router/issues/2172, which I expect to have somewhat different semantics that instead tie into specifics of the router.

I'm not sure where the priority on this one sits, though - a naive implementation of relative transition paths opens a whole can of worms with how the router currently is entirely indifferent to trailing slashes.

**Comment by yanivtal** [comment]
I'm surprised more people aren't asking for this. It's awfully leaky to have components aware of their absolute paths. Are there other workarounds I'm unaware of or is everyone tightly coupling their routes like an exoskeleton that can never change?

**Comment by taion** [comment]
Don't they already sort of work when using `createBrowserHistory`? I don't know that we'll meaningfully resolve this before we figure out the appropriate semantics on the router side, and those are non-trivial.

**Comment by yanivtal** [comment]
Thanks for the update. I did some more experimentation and I'm getting some weird behavior. When I'm on /base-route and i call history.push('subpath'), the URL updates to /base-route/subpath but nothing happens and I get an error saying 'subpath' doesn't match any routes. When I refresh the page, the route loads properly..

**Comment by taion** [comment]
I never said the router supported it.

**Comment by yanivtal** [comment]
Ahh just weird because they punted here in https://github.com/rackt/react-router/issues/1828#issuecomment-139073817. Guess work's for them?

**Comment by taion** [comment]
Router discussion is on https://github.com/rackt/react-router/issues/2172. There's really a number of complexities here.

**Comment by yanivtal** [comment]
Cool thanks for the right link!
