### ISSUE TITLE
Restoring URL on cancelled transition doesn't work after refresh

### ISSUE THREAD

**Issue by taion** [mjackson/history#157]
This logic: https://github.com/rackt/history/blob/v1.13.1/modules/createHistory.js#L133-L135

The issue is that `allKeys` is tracked purely in-memory. If I refresh, then go back, the `allKeys` array is empty, and we bail past this logic.

We should probably track a per-session `allKeys` in something like session storage when possible. This would also give us a principled way to resolve the edge cases in https://github.com/rackt/history/pull/104 (since we can index that session-stored `allKeys` array to find the oldest stored states for the current session/stack).

**Comment by taurose** [comment]
Also see #28 .

The work in https://github.com/rackt/react-router/issues/843 resulted in `location.key` and `allKeys` minus the persistence and `location.current`.

**Comment by taion** [comment]
Hah! Yeah. Sorry - a bit hard to keep track of issues across both repos except for the ones I've personally seen before.

Implementation outline - for each history entry, associate to `location.key` (in session storage or whatever) a "session key". This "session key" is persistent through the session.

Then we can just pick up the session from the session key that we keep around in the session store, and use it to replace https://github.com/rackt/history/pull/104.

**Comment by taurose** [comment]
Yeah, my bad for not following that up with a PR or issue. Implementation outline sounds right.

Another thing we could do with this to clean up sessionstorage is to remove unreachable states whose browser entries are purged after a PUSH.

**Comment by taion** [comment]
Unless one of us feels super inclined to fix this, I don't think this is especially high priority to fix - something like the above could improve a few things, but the complexity is out of line with the benefit a bit. We should fix these bugs at some point, but they're hard to get worked up about.

**Comment by maisano** [comment]
it'd be great to see this fixed–i'd be willing to submit a patch for it sometime this week.

does it make sense to expose `getCurrentIndex` on history so it can be handled/overridden accordingly? it might be nice to open up that function to to enhancers as well.

**Comment by taion** [comment]
I see your https://github.com/mjackson/history/pull/293 but it's not enough – we need to actually persist something like a list of locations to session storage. Right now the issue is that `allKeys` in https://github.com/maisano/history/blob/1f562555bab5531b15ef5f13b441d3a060ad5328/modules/createHistory.js#L25 lives only in-memory.

**Comment by maisano** [comment]
@taion #293 is a bugfix unrelated to this issue.

**Comment by taion** [comment]
Ah, okay.

**Comment by maisano** [comment]
i just realized my reply was a bit terse. hopefully it wasn't rude.

regarding tracking `allKeys` in session storage, would we want to limit this behavior to browser history? or is it something we should attempt to track in all versions of history?

**Comment by taion** [comment]
No worries. Ideally we'd track it in all DOM histories but hash history and state interact oddly.

**Comment by stefanomasini** [comment]
Any chance this bug would be addressed soon? I'm using "history" outside of the context of react-router. I have the following problem:

1. load my app from url A
2. go to url B
3. reload the app
4. click the browser back button

At this point the url bar goes back to showing url A, but my application is not notified, so the view is stuck at page B. I think this is due to the bug described here, right?

Any suggested workaround?

**Comment by mjackson** [comment]
I don't think we'll solve this any time soon. For now, it's just a limitation of our implementation.
