### ISSUE TITLE
use of replaceState in getCurrentLocation causes document.referrer to become an empty string in IE

### ISSUE THREAD

**Issue by dbellizzi** [mjackson/history#220]
https://github.com/rackt/history/blob/master/modules/createBrowserHistory.js#L42

The use of replaceState on this line causes IE to turn whatever document.referrer was into an empty string.  The same doesn't happen in Chrome.

When used with react-router 1.0 and above, this causes all initial page hits to discard document.referrer in IE

**Comment by ryanflorence** [comment]
which version of IE? All?

**Comment by taion** [comment]
I don't see that there's anything we can really do about this – we need to have `location.key` set to something for everything downstream to work.

Can we just document this? You'll need to handle this on your side, e.g. by reading `document.referer` before initializing the router.

**Comment by dbellizzi** [comment]
I've tested in IE11 and reproduced the issue, but from our traffic info, I suspect other previous versions.

As for working around it, I can with some difficulty because we're using custom tracking, but other analytics packages, Google Analytics, Mixpanel, etc. probably can't be worked around.

**Comment by taion** [comment]
Can't you just make sure your analytics scripts run before you render the `<Router>`?

**Comment by dbellizzi** [comment]
Interaction with the page triggers analytics events.  We can run the page view event before ``<Router>`` to capture the referrer, but subsequent events in IE are missing referrer.

My workaround is to capture the referrer before router and then pass it along everywhere for the later events.  I can do that in my tracking system, and it looks like you [can do it in Google Analytics too](https://developers.google.com/analytics/devguides/collection/gajs/methods/gaJSApiCampaignTracking#_gat.GA_Tracker_._setReferrerOverride).

It's a subtle bug though, you don't know that you've introduced it until you start looking at data and notice something funny happened when you upgraded react-router, and by then there's bad data in your analytics system.

**Comment by taion** [comment]
@dbellizzi Well, okay, what do you think we can/should do on our end here? I'm not sure what our options are – it doesn't seem like there's anything we can do to disable IE blanking the referer.

**Comment by dbellizzi** [comment]
I'm not too familiar with this codebase, but the only option I see is avoiding replaceState on the initial load.  if you're trying to generate a key for the initial page load and using replaceState to store it, is there a way to store that key somewhere else for that first load, then fall back to looking there when it can't be found in the history state?  If the current path matches the path you are about to push, and there's no key, they put the key somewhere else, in a closure, or put it on history, or a data attribute on body?

I'm not sure how feasible this is.  I'm coming at this from a consumer of react-router, which didn't have this issue prior to the 1.0 release, but still has browser history support.  Maybe the new functionality fixes other bugs, but it does introduce this new one.

**Comment by taion** [comment]
But this will happen anyway the next time anybody causes `replaceState` to be called.

**Comment by mjackson** [comment]
This is fixed in f12d632691ebef652d0cf5dd67a033e87746fc4a. We no longer require the initial POP to have a key, for various reasons.

**Comment by dbellizzi** [comment]
That is great news, I really appreciate it.  Thanks for the help.
