### ISSUE TITLE
When using base tag, react-router and redux-devtools, Uncaught SecurityError: Failed to execute 'pushState' on 'History' occurs

### ISSUE THREAD

**Issue by narr** [mjackson/history#234]
When base tag is used like "http://localhost:3000/", in addBasename function from useBasename.js 
location.basename is set to '/' and location.pathname is also set to '/' if the location.pathname is '/'.
The problem is that when it reverts to the path '/' by redux-devtools with react-router, it uses locationBeforeTransitions object which is the location object from history and the path becomes '//' in finishTransition function from createBrowserHistory.js and it cause an error like below at window.history.pushState(historyState, null, path) in finishTransition function.

Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://localhost:3000'.

I guess location.pathname should be set '/' only when location.basename is not '/' so that the path in finishTransition function will be '/'.
<img width="591" alt="screen shot 2016-02-18 at 3 52 30 pm" src="https://cloud.githubusercontent.com/assets/1445566/13135849/acdfaaea-d657-11e5-8e19-4aa09f173682.png">

**Comment by taion** [comment]
The correct fix here is probably to use `addBasename` in `transitionTo` on `useBasename`.

That said, we're not going to accept a PR here without tests.

**Comment by mjackson** [comment]
Looks like conversation has stalled here.

**Comment by mwq27** [comment]
I'm having this same problem.  Was there a solution?

**Comment by jonaskello** [comment]
Having the same issue. Any solution yet?

**Comment by JMStudiosJoe** [comment]
My solution was taking path from one state
var helloState = {
  name: 'hello',
  url: '/login',
  component: LoginComponent
}
and changing it to 
var helloState = {
  name: 'hello',
  url: '#/login',
  component: LoginComponent
}
