### ISSUE TITLE
When create a <Link> with a `hash` only parameter I got 'undefined' on <a href= ". .."> output

### ISSUE THREAD

**Issue by bySabi** [mjackson/history#244]

**Comment by taion** [comment]
This has absolutely nothing to do with this library.

**Comment by bySabi** [comment]
@taion `createHref` it is not a `history` function ?

**Comment by bySabi** [comment]
@taion @mjackson 
The problem is on this function: https://github.com/mjackson/history/blob/v2/modules/createHistory.js#L162

Can you fix this and publish a v2 update before release v3??

thanks.

**Comment by taion** [comment]
This is an incorrect usage of the API on your end. Please follow up on an appropriate support forum.
