### ISSUE TITLE
createPath returns invalid path when `pathname` is undefined

### ISSUE THREAD

**Issue by safareli** [mjackson/history#245]
if you call `history.createHref({search: '?foo=bar'})` it returns `undefined?foo=bar`.
possible fix would be to apply this diff to [PathUtils.js#L80](https://github.com/mjackson/history/blob/master/modules/PathUtils.js#L80):
```diff
-  let path = (basename || '') + pathname
+  let path = (basename || '') + (pathname || '')
```

if the solution is ok i could create a PR.

**Comment by taion** [comment]
That's going to do something really weird if you do have a `basename`, though. I think this is really just something we should consider for #135.

**Comment by safareli** [comment]
Kinda did not get your point. why is it going to do something weird? if you have `basename` and `pathname` is still `undefined`, output of `createPath` will still contain undefined.
i think it's better to have empty string for `pathname` instead of `undefined`

**Comment by taion** [comment]
See #135.

**Comment by safareli** [comment]
I don't use `react-router` i just use `History` and didn't get why #135 is related to this issue :/

**Comment by taion** [comment]
We want to treat undefined path as relative. While in the no-basename case, `?foo=bar` might be an okay path, `/basename?foo=bar` for an undefined path doesn't make sense to me.
