### ISSUE TITLE
Using base element can have hard-to-track side effects

### ISSUE THREAD

**Issue by darobin** [mjackson/history#246]
The [documentation](https://github.com/mjackson/history/blob/master/docs/BasenameSupport.md#using-base-href) recommends using the `<base>` element as a way of avoiding having to pass a `basename` in. There are indeed plenty of cases in which that will work well; there are, however, cases in which it will have knock-on effects that will be hard to track down.

In our case for instance `base` worked for everything but it had a strange interaction with references to SVG gradients. Since the two features were designed separately, detecting the cause of the problem took us a while.

I'm happy to PR this, I just wasn't sure if you preferred removing that advice or keeping it with a caveat.

**Comment by taion** [comment]
For my benefit, can you elaborate on what the specific edge cases here are?

**Comment by trodrigues** [comment]
This is a known problem of using SVGs while using a base element (see http://stackoverflow.com/questions/18259032/using-base-tag-on-a-page-that-contains-svg-marker-elements-fails-to-render-marke/18265336#18265336)

Using inline SVGs is also an alternative.

All in all I don't think this issue is history related at all.

**Comment by darobin** [comment]
@trodrigues This issue actually applies to inline SVG as well (it shouldn't, but apparently the base affects the resolution with `url()` but not that of the `id` of the resource in the same document). Succinctly:

```
<svg>
  <linearGradient id="foo">...
  <rect fill="url(#foo)">...
</svg>
```

Will not resolve in the presence of `base`.

As indicated in the original report, I make no claim that this is an issue with history code, simply with the docs. I'm happy to provide a warning.

**Comment by taion** [comment]
It's somewhat history-related because we now encourage you to use `<base>` to configure a basename, because we want to make the built-in history singletons in React Router v2.x useful.

**Comment by trodrigues** [comment]
@darobin ah, that's not exactly what I meant, it was more in the line of not using references to other SVG elements at all and make sure all of it is generated and inlined. This might not sound like such a great idea but if you can generate JS modules with that SVG code then size and reusability is less of a concern.

But yeah, I agree, having some warnings of what works differently in the presence of <base> is not a bad idea.

**Comment by mjackson** [comment]
Thanks for the heads up, @darobin. I'd be happy to merge a PR to make the docs more helpful if you're still up for it.
