### ISSUE TITLE
query-string@3.0.2 causes `[TypeError: object.hasOwnProperty is not a function]`

### ISSUE THREAD

**Issue by SpainTrain** [mjackson/history#247]
This is a heads up that the dependency `query-string` at version 3.0.2 has a different return value for the parse method than 3.0.1 did - https://github.com/sindresorhus/query-string/issues/50.  Specifically, it causes line https://github.com/mjackson/history/blob/master/modules/useQueries.js#L13 to throw `[TypeError: object.hasOwnProperty is not a function]`.

It appears that calling `hasOwnProperty` on the object returned from `parse` will not be supported going forward (since a qs param could be named `hasOwnProperty`).

**Comment by taion** [comment]
I put up https://github.com/mjackson/history/pull/248 (against v2). Let's see how https://github.com/sindresorhus/query-string/issues/50 goes – if @sindresorhus doesn't roll back that change, we'll need @mjackson to publish a new v2.x release.

**Comment by sindresorhus** [comment]
Sorry, fixed in 3.0.3.

**Comment by mjackson** [comment]
np, thanks for the quick fix @sindresorhus :D
