### ISSUE TITLE
add support for hashes without leading slash

### ISSUE THREAD

**Issue by zdila** [mjackson/history#249]
`createHashHistory` could have an option to prevent leading slash in the hash.

Instead of `index.html#/foo` the URL would then be `index.html#foo`.

**Comment by taion** [comment]
Might be worth thinking about this in conjunction with https://github.com/mjackson/history/pull/131 and https://github.com/reactjs/react-router/issues/601. It sounds like we need some flexibility in supporting various hash URL schemes to both offer appropriate legacy support and allow interop with e.g. Auth0.

**Comment by mjackson** [comment]
That's not a bad idea, @zdila, but it introduces extra complexity for not a lot of gain IMO. I think I'd rather leave it as it is now unless there's a stronger argument than aesthetics.

**Comment by zdila** [comment]
Aesthetics is a strong argument nowadays :-). In any case we'll try to implement our own HashProtocol then because feature we request is a critical issue for our customer.
