### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by janecakemaster** [mjackson/history#259]
the installation fails on the dependency `mdns2` with error `Failed at the mdns2@2.1.4 install script 'node-gyp rebuild'`

node 5.9.1
osx el capitan

**Comment by taion** [comment]
wffm

**Comment by janecakemaster** [comment]
You should probably address a breaking dependency. Have you tried installing `mdns2` on your machine?

**Comment by janecakemaster** [comment]
I don't see how you can close and dismiss this so quickly. Shouldn't the package maintainers make sure that their dependencies are up to date and not breaking the build, on the latest versin of node and npm?

**Comment by janecakemaster** [comment]
If you don't plan on keeping things up to date please mention that somewhere please!

**Comment by taion** [comment]
`npm i history` works just fine for me in a fresh environment, as does `npm i` from a fresh Git clone.

I don't see `mdns2` as a dependency anywhere either in production or in development dependencies.

Please verify that you're not making an error on your end before pointing the finger of blame.

**Comment by taion** [comment]
And that includes transitive dependencies:

```
jjia@jjia-mbp:~/vendor/history (master=)$ npm ls | grep dns
jjia@jjia-mbp:~/vendor/history (master=)$
```

You almost certainly have something misconfigured on your end.

**Comment by janecakemaster** [comment]
welp i feel like a turd. the `-S` flag doesn't work it seems. a million apologies :sob:

**Comment by taion** [comment]
No worries (: Good luck.
