### ISSUE TITLE
Don't use strict URL encoding

### ISSUE THREAD

**Issue by wmertens** [mjackson/history#260]
See https://github.com/sindresorhus/query-string/issues/42

Browsers are much more lenient than the apparent spec for URLs, so it would be great if history could set the (new) `strict` option of query-string's `stringify` to `false`.

Code and output example: https://github.com/sindresorhus/query-string/blob/e7b42c138256447754ff8b52369acfaec6c4969b/test/stringify.js#L47-L55

**Comment by taion** [comment]
This feels wrong to me as a default – I don't feel the need to really second-guess what `query-string` does as its default behavior. You can override the default yourself, though.

**Comment by wmertens** [comment]
Somehow I completely missed the API for specifying your own conversion, sorry for the noise.
