### ISSUE TITLE
How to get current location without history.listen?

### ISSUE THREAD

**Issue by luqin** [mjackson/history#261]
How to get current location without history.listen?

**Comment by taion** [comment]
This is impossible by design with 1.x and 2.x, as we want the history API to be stateless.

**Comment by erwingaitano** [comment]
You should remove the getCurrentLocation references from the docs.

**Comment by taion** [comment]
The docs refer to the 3.x prerelease, not to 1.x or 2.x.

**Comment by luqin** [comment]
:+1:
