### ISSUE TITLE
How can I push a previous location onto the history stack?

### ISSUE THREAD

**Issue by tsemerad** [mjackson/history#266]
I'm trying to call `history.push()` to push my user back to the previous page. Of course there's `history.goBack()` which would take them there, but that puts them at an earlier place in their browser history, which I don't want. I want to push that previous location onto the end of the history stack, just like any other `history.push()`. Is there a simple way to do this?

**Comment by taion** [comment]
That's not generally possible. Consider using `location.state` to track the previous location explicitly. You can check the React Router auth-flow example for a related implementation.

**Comment by ryanflorence** [comment]
Just push them to that location. `history.push(previousLocation)`

**Comment by tsemerad** [comment]
Ok. Thanks for the advice. I was hoping there was something like a `history.get(-1)` function that could retrieve a previous location. I'm pretty inexperienced when it comes to browser history, so I assumed there would be a way to retrieve the location information on any arbitrary history item. I'll just track the previous location explicitly. Thanks for the clarification.
