### ISSUE TITLE
How to get current location

### ISSUE THREAD

**Issue by hhhyaaon** [mjackson/history#270]
I create a history object as follow:
```
var _History = require("history");

History = _History.createHistory()||{};
```
And the Docs show that can get current location by using method `getCurrentLocation`
![image](https://cloud.githubusercontent.com/assets/17123400/14419301/85a0bb76-fff7-11e5-8bcb-a344e43f81d3.png)

However,I try to console the History object  I create, getCurrentLocation don't exsist 
![image](https://cloud.githubusercontent.com/assets/17123400/14419362/f79a0714-fff7-11e5-8cbd-7ae2a3314824.png)

**Comment by taion** [comment]
Docs on master refer to master, not release.
