### ISSUE TITLE
Allow to more-easily preserve queryString upon navigation (minor, API)

### ISSUE THREAD

**Issue by slorber** [mjackson/history#272]
Affects: history 2.0.1

I'd like to be able to preserve some parts of the queryString upon navigation (ie for all push/replace or ReactRouter links)

I've seen the `useQueries` here: https://github.com/mjackson/history/blob/master/docs/QuerySupport.md

I can use that for my usecase but it seems not so easy because it requires to override existing parse/stringify through options.

```javascript

import { stringify } from 'query-string'
const defaultStringifyQuery = (query) =>
  stringify(query).replace(/%20/g, '+')


const preservedQueryStringParams = {
  publicPreview: true
}

const history = useQueries(createHistory)({
  stringifyQuery: function (query) {
    const merge = {...query,...preservedQueryStringParams}
    return defaultStringify(merge)
  }
})
```

I'd like to do something like that, but actually the defaultStringify is not exported so as you see it requires me to dupicate some code of `defaultStringifyQuery` to solve my usecase. Not a big deal but I think it could be simpler

**Edit**:

After some attempts I did not sucess to use the following because of:

```javascript
    function appendQuery(location, query) {
      const searchBaseSpec = location[SEARCH_BASE_KEY]
      const queryString = query ? stringifyQuery(query) : ''
      if (!searchBaseSpec && !queryString) {
        return location
      }
```

I can't solve my usecase by providing a `stringifyQuery`, because this function never gets called (because normally my links don't have a queryString.

But replacing this line ` const queryString = query ? stringifyQuery(query) : '''`  by  ` const queryString =  stringifyQuery(query || {}) ` do solve the problem.

# Concrete usecase

I have an app when users login to create content. Content has url like that:

```
https://www.app.com/content/234233442/some-content-related-slug
```

The user can then publish content any make it publicly available (ie you don't have to be logged in. Then the exact same url will open 2 different apps (one app is for logged-in users, the other is for anonymous users).

But for logged-in users, I want then to be able to browse their newly published content as if they were anonymous, so I created this url with a `?publicPreview` queryString

```
https://www.app.com/content/234233442/some-content-related-slug?publicPreview
```

The problem is that upon navigation, that queryString gets lost, and if the user navigated and then refresh, he returns to the connected app. I'd like this `?publicPreview` queryString be preserved upon all kind of navigations that occur in the app.

**Comment by mjackson** [comment]
@slorber You could possibly write a custom [history enhancer](https://github.com/mjackson/history/blob/master/docs/Glossary.md#createhistoryenhancer) and use it like

```js
const history = usePublicPreview(useQueries(createHistory))()
```

This way you could take advantage of the built-in query serialization without needing to know about our internals.

**Comment by slorber** [comment]
yes I'm thinking about building something kind of generic like `useDescriptionLocatorModifier` so that I can more easily build other useful things on top of it
