### ISSUE TITLE
Support for multiple origins

### ISSUE THREAD

**Issue by arbesfeld** [mjackson/history#275]
I'd like to use this module for managing state transitions inside of an embedded iframe. This iframe can navigate to various domains / origins, but these origins are stripped by the library. 

What is the recommended way with dealing with multiple origins? Is this out of the scope of the library, ie. should I manage this separately by using the `state` object?

**Comment by taion** [comment]
This is actually not possible – the HTML5 history API explicitly disallows transitioning outside of origins and will raise a `SecurityError` if you try.

Just use the `window.location` based API instead – it sounds like you actually want to navigate rather than to trigger SPA-style navigation.

**Comment by arbesfeld** [comment]
Thanks for the quick response @taion!

Should clarify more I suppose: I am hoping to use this to "simulate" a SPA by triggering transitions between iframes. For example, I'd like to be able to write:

`history.push('https://foo.com')`, and have my app push a new iframe with `https://foo.com` on top of the current window. I could obviously build this sort of system myself but I'd like to leverage this library as much as possible.

Does that make sense? Could go into more detail if that would be helpful.

**Comment by taion** [comment]
That's not really what this library does – this library manages interacting with the browser history state, without changing what's actually rendered on the page. You could pass that down with `location.state` into a component wrapping an `<iframe>` or something, like you said, but actually updating the contents of the page and e.g. re-requesting to the server is in some sense the opposite of what this library is intended to do.
