### ISSUE TITLE
history.listen stops listening on hash changes v1.17.0

### ISSUE THREAD

**Issue by uptownhr** [mjackson/history#276]
This is kind of a strange scenario and detailed steps below. I'm using react and listening on history changes on the componentWillMount life cycle method. Everything works fine and is good. I can can pushstate, change query params, all the events are being catched. 

However, after the component is unmounted and the user returns using `back`. I can see the componetWillMount events occur, and I can even see that my unListener is available. However, `#changes` will not cause listen even to trigger. Other history changes using history.push are caught by the listener event.

Would be great to know if others on different version are also experiencing this.

Steps to reproduce.
1. on componentWillMount listen on history changes and create an unlistener
2. update your url by adding `#something` hash to it
3. notice that the listener event is triggered

4. go to a url where the componetWillUnmount will be triggerd
5. Press `back`
6. Attempt to update the url again with `#something` hash
7. Notice the listener does not trigger anymore

8. Call history.pushState
9. Notice listener event is triggered

For step `#4`, I've attempted to call  the unListen and not calling it. Both scenarios result in the same behavior. 

Please help

Thanks

**Comment by taion** [comment]
This is still a bit confusing. Could you post a runnable example?
