### ISSUE TITLE
Support for custom addBasename in useBasename 

### ISSUE THREAD

**Issue by marcelalburg** [mjackson/history#279]
Hello,

i use the feature addBasename in my project and it works super. now, i need a possibility to write some custom code in addBasename.

when the customer goes to my project, he see the startpage / (in my JS, i defined "/de" as basepath dynamically). After one click, the customer see in the url path /de/site and with the click on the logo (home link), the page is /de/.

i want change just the home link that this one stays / instead of /de

a possibility is to allow a custom function in addBasename.

currently, i add

      if (!location || location == '/')
        return '/'

to prependBasename in https://github.com/mjackson/history/blob/master/modules/useBasename.js and it works for me

Thanks
Marcel

full code of prependBasename:

    const prependBasename = (location) => {
      if (!basename)
        return location

      if (!location || location == '/')
        return '/'

      const object = typeof location === 'string' ? parsePath(location) : location
      const pname = object.pathname
      const normalizedBasename = basename.slice(-1) === '/' ? basename : `${basename}/`
      const normalizedPathname = pname.charAt(0) === '/' ? pname.slice(1) : pname
      const pathname = normalizedBasename + normalizedPathname

      return {
        ...location,
        pathname
      }
    }

**Comment by taion** [comment]
What you're describing sounds less like a basename and more like something you want to handle in your routing layer. The basename is intended for the actual base, which is not what you are doing here.

**Comment by taion** [comment]
What I mean is – your basename is actually empty, and it's more like you have some routes under `/de`.

**Comment by marcelalburg** [comment]
Hello, thanks for your fast answer. Sorry, but i don't understand it correctly and maybe, you've more detailed information about your router solution.

I'll describe my plan more in detail.

The customer comes to the main page unter / and the js detect his language (via browser settings) and set the basename to (p.e.) /de

the hole other page stay like it is:

the router:

```
<Route path='/' component={RootLayout}>
  <IndexRoute component={IndexView}/>

  <Route path='/news/' component={NewsView}/>
  <Route path='/news/:pageName' component={NewsDetailView}/>
</Route>
```

in my components i can use 

```
<Link <Link to="/news/test">test news</Link>
```

and the basename logic preprend the /de path in front of all links. 

What i just want is that the customer is not confused, when he go back to home and the link is /de instead of /

And for that, my change in the prependBasename function works well.

Thanks
Marcel
