### ISSUE TITLE
Unsubscribing from all listeners

### ISSUE THREAD

**Issue by volkanunsal** [mjackson/history#280]
Is it possible to add a method to let us unsubscribe from all listeners? It could be something like this:

```javascript
const history = createHistory()
history.listen(..)
history.unlistenAll()
```

The rationale for this endpoint is that it would make integration with other libraries a lot easier. Personally I need to use Turbolinks in addition to react-router, but I can't simply re-render all my routes in docready anymore because react-router binds event handlers every time it's mounted to the page. If only there was a way to unsubscribe all events from history before rendering the routes, I could easily use both libraries. As it is, I'm having to roll out my own `createHistory` function, which is not ideal.

**Comment by taion** [comment]
Might be better to do this in a history enhancer. I do think it's a bit messy to force an unsubscribe of listeners you may not know about in general – plus this is easy to do in an enhancer (just track all the listeners).

**Comment by volkanunsal** [comment]
@taion Like this?

```javascript
/**
 * Returns a new createHistory function that may be used to unlisten
 * from all listeners.
 */
const useUnlistenAll = (createHistory) =>
  (options = {}) => {
    const history = createHistory(options)

    let unlisteners = []
    const listen = (listener) => {
      let unlisten = history.listen(location => listener(location))
      listener.push(unlisten)
      return unlisten
    }

    const unlistenAll = () => {
      unlisteners.forEach(unlisten => unlisten())
    }

    return {
      ...history,
      listen,
      unlistenAll
    }
  }

export default useUnlistenAll
```

**Comment by taion** [comment]
@volkanunsal 👌👀💯

(exactly)

**Comment by volkanunsal** [comment]
👍  Thank you!
