### ISSUE TITLE
History.length

### ISSUE THREAD

**Issue by tommoor** [mjackson/history#286]
It would be great to have some way of inspecting the history, I'd like to be able to do something like the following:

```javascript
if (history.length > 0) {
  history.goBack();
} else {
  // display something else
}
```

Length would be enough, but others might find a method to return the history stack itself useful? Perhaps I'm missing an API - but really can't see anything exposed in the docs.

**Comment by taion** [comment]
Some earlier discussions: https://github.com/reactjs/react-router/pull/843, https://github.com/mjackson/history/issues/89, https://github.com/reactjs/react-router/issues/767, https://github.com/reactjs/react-router/pull/1376#issuecomment-118185067.

Unfortunately there's a lot of complexity in doing this right now, so we don't have a really great way forward on this.
