### ISSUE TITLE
Question about compatibility

### ISSUE THREAD

**Issue by littlee** [mjackson/history#290]
What browser features are required if I want to use “history”?

I notice that some popular browser (UC web) in my country does not implement features like `history.state`

```js
history.state //return undefined
```

can those browser works with “history”?

**Comment by taion** [comment]
You'd have to use hash history or the refresh-based browser history if `history.state` is not supported. You can look at the test suite to see which browsers we test against.

**Comment by littlee** [comment]
Thanks for replying
