### ISSUE TITLE
Should object location descriptors require a pathname when using basenames?

### ISSUE THREAD

**Issue by natelaws** [mjackson/history#294]
When history is configured using a basename you must specify a pathname when doing a transition.  i.e. `history.replace({ pathname: '/', state: { redirectTo: 'http://www.foo.com'  } })`

I would like to be able to just do `replace({ state: { redirectTo: 'http://www.foo.com'  } })` in react-router.  However that naturally throws a "TypeError: Cannot read property 'charAt' of undefined" pointing to https://github.com/mjackson/history/blob/85e4b96650335afeceb2d268fda2e33907036f8a/modules/useBasename.js#L35

Is this something that should be supported or just documented?

**Comment by taion** [comment]
Location descriptors are intended to always require a `pathname`.
