### ISSUE TITLE
createLocation is not present in your mudule any more

### ISSUE THREAD

**Issue by darkfrontcode** [mjackson/history#302]
Hey man, I install latest version of you module, but, createLocation is not present any more. I try any ways, like import { createLocation } from 'history', or call from history.createLocation and nothing. Can U help me? Thank you.

**Comment by taion** [comment]
The top-level one has been deprecated for a long time now. It's on history objects now.

**Comment by darkfrontcode** [comment]
you mean this project? https://www.npmjs.com/package/object-history or another thing?

**Comment by chentsulin** [comment]
https://github.com/mjackson/history/blob/master/modules/createHistory.js#L161

**Comment by darkfrontcode** [comment]
Thank you my friend =}

**Comment by calvinl** [comment]
@darkfrontcode @chentsulin @taion How do we get `createLocation` for environments with no DOM? It's not present in the top level anymore.

It's also still listed in https://github.com/ReactJSTraining/history/blob/master/docs/Location.md#programmatic-creation

**Comment by taion** [comment]
That's a docs bug then. Creating a location without a history object (which need not require a DOM, e.g. with memory history) has been deprecated for a while, because location creation depends on history enhancers/&c.

**Comment by calvinl** [comment]
@taion thanks -- good to know!

**Comment by shark0der** [comment]
For others that were wondering how to do this on server side:
```
const location = createLocation(req.url);
match({ routes, location }, (error, redirectLocation, renderProps) => {
```
becomes:
`match({ routes, location: req.url }, (error, redirectLocation, renderProps) => {`

Credits to @calvinl for referencing this issue in his commit.
