### ISSUE TITLE
When is a new release coming?

### ISSUE THREAD

**Issue by gustavnikolaj** [mjackson/history#352]
Sorry if this is not the right place or way to ask, but I'm curious when a new release will be published to npm?

I'm currently blocked on the issue fixed by #301 which is landed on master, but not yet released.

Unfortunately I'm not even able to use it as a git dependency because the package.json files array does not contain the modules folder. So I have to rely on manually linking in the dependency.

**Comment by jmurzy** [comment]
This is a blocker for me as well. 😑

**Comment by mjackson** [comment]
I'll cut a new release today. Sorry for the blockage, guys.

**Comment by mjackson** [comment]
Boom. Just released [3.1.0](https://github.com/mjackson/history/releases/tag/v3.1.0).

**Comment by taion** [comment]
Really need to merge and cut a release with https://github.com/mjackson/history/pull/316 at least. The semantics around `location.key` are quite broken with hash histories right now.
