### ISSUE TITLE
Leading slash not always automatically appended

### ISSUE THREAD

**Issue by grassick** [mjackson/history#368]
In previous versions, history.push("") would put a leading slash before the location change was called, effectively cleaning up the pathname. It seems in 4.x, it doesn't, meaning that the path "/" no longer matches.

**Comment by grassick** [comment]
Also, "?" is not pre-pended to location.search. An error on the user's side, obviously, but it would be nice if the location was sanitized.

**Comment by mjackson** [comment]
Thanks, @grassick. These were both oversights. I'll cut a patch release with the fixes.

**Comment by mjackson** [comment]
Both fixes released in v4.1.0.
