### ISSUE TITLE
Location pathname is not always absolute

### ISSUE THREAD

**Issue by puradox** [mjackson/history#375]
According to MDN, 
> `Location.pathname` Is a DOMString containing an initial '/' followed by the path of the URL. ([source](https://developer.mozilla.org/en-US/docs/Web/API/Location))

According to the HTML Standard, as part of the `Location.pathname` getter requirements,
> Return "/", followed by the strings in url's path (including empty strings), separated from each other by "/". ([source](https://html.spec.whatwg.org/multipage/browsers.html#dom-location-pathname))

The function `createLocation()` ([located here](https://github.com/mjackson/history/blob/master/modules/LocationUtils.js#L4)) does no such check for an absolute pathname. Instead, it allows users to create a `location.pathname` without the initial "/" character. 

For me, this led to some unexpected behavior when I was calling `browserHistory.push()` with the relative pathnames from the location object to capture `react-router` URL parameters:

```
browserHistory.push(location.pathname + '/' + additionalPath);
```

Is this an intentional difference from the specification?

**Comment by mjackson** [comment]
Which version of history are you using? `location.pathname` should always be absolute.

**Comment by puradox** [comment]
@mjackson This is relevant to the latest version of `history` hosted on npm, `4.3.0`. Here is the simplest way I can create a location without an absolute pathname:
```
const history = require('history');
const location = history.createLocation({ pathname: 'foo/bar' });
console.log(location.pathname); // Prints "foo/bar"
```

**Comment by mjackson** [comment]
`createLocation` is not designed to automatically make all paths absolute. It's not even recommended to use it at all in userland. That method mainly exists for library code, like react-history and react-router.

Every `location` you get from `history.listen` should be absolute, same as `window.location.pathname`. That's the only guarantee we provide.
