### ISSUE TITLE
hashHistory and baseName

### ISSUE THREAD

**Issue by nibblesnbits** [mjackson/history#376]
I've noticed something in [react-router](https://github.com/ReactTraining/react-router) that I believe can be traced back to this library.  [This issue](https://github.com/ReactTraining/react-router/issues/3839) covers some of it, and [my comment](https://github.com/ReactTraining/react-router/issues/3839#issuecomment-253605632) shows the specific scenario.

Basically, (unless I misunderstand the purpose) when using `hashHistory`, `href`s with a `basename` should produce paths like `/my-basename/#/my-page`, but the current behavior seems to be `/#/my-basename/my-page`.  I see the value in the latter behavior, but for applications that exist at a subdirectory, the `/my-basename/#/my-page` path is what I need.

I've also noticed that there seem to be no unit tests related to the use of `basename` in the repo.  If the `/my-basename/#/my-page` behavior is the correct behavior, would you be open to a PR with these changes?

**Comment by mjackson** [comment]
What version of history are you using? `basename` in hash history is redundant and should probably be removed altogether since you can always control exactly what the hash is. It should only ever be needed when using browser history.

**Comment by nibblesnbits** [comment]
So in this scenario I'd be setting the hash itself to `my-basename/#`?

**Comment by mjackson** [comment]
Ah, sorry. Scratch what I said earlier. `basename` does actually have value in the hash context because it sets the prefix for the hash.

In your case, the page that you're using should already be served at the `/my-basename/` URL path. So any URLs that are generated with a hash should be relative to that URL already.

**Comment by afilp** [comment]
@mjackson So, from your answer you mean that us that use the HashHistory we do not really need to care about the basename? It appears that all basename does is to be added *after* the hash not before the hash, so it does not really change something in order to use it.
