### ISSUE TITLE
deepEqual is broken when A is object and B is null

### ISSUE THREAD

**Issue by aaronjensen** [mjackson/history#378]
I'm running into this an issue w/ react-router v4 and I tracked it down here.

The problem is here, I believe: https://github.com/mjackson/history/blob/929d5dca576512ab698486c98a3cb063e9a17ca9/modules/LocationUtils.js#L64-L66

```
     TypeError: Can't call method on  null
       exports (http://localhost:4002/js/vendor.bundle.js:1043)
       exports (http://localhost:4002/js/vendor.bundle.js:799)
       keys (http://localhost:4002/js/vendor.bundle.js:25618)
       looseEqual (http://localhost:4002/js/bundle.js:744)
       locationsAreEqual (http://localhost:4002/js/bundle.js:757)
# StaticRouter's componentWillReceiveProps
       componentWillReceiveProps (http://localhost:4002/js/bundle.js:102)
```

The next (or B) state property is null, but because A's state is an object, deepEqual attempts to call `Object.keys(null)`

```
state {"pathname":"/signin","search":"","hash":"","state":{"from":{"pathname":"/home","search":"","hash":"","state":null,"query":null}},"query":null}
next {"pathname":"/signin","search":"","hash":"","state":null,"query":null}
```

I don't know if I'm doing something wrong that's causing `state` to be null, but `deepEqual` should probably be resilient to this. Thoughts?

**Comment by aaronjensen** [comment]
@mjackson I'm happy to pull request this if you give me some guidance on how this is supposed to work. It seems like `state` starts out as null. This doesn't appear to be a problem in chrome, but is in phantomjs so it breaks our automated tests. I can simply make `looseEqual` resilient to this case, which will make this work. Is that ok?

**Comment by mjackson** [comment]
I actually just shipped a small package the other day, https://github.com/mjackson/value-equal, which I was hoping to use here instead of including my own `deepEqual` function in `history`. I believe that package should fix your issue, but I haven't gotten around to swapping it in yet.

Would you like to take a stab at it?

**Comment by mjackson** [comment]
BTW, I think a separate package there makes sense so we can test it independently of the `history` library's concerns.
