### ISSUE TITLE
Where did listenBefore go?

### ISSUE THREAD

**Issue by fredva** [mjackson/history#379]
We are currently on version 2.1.1. We use using `history.listenBefore` to track page views in Google Analytics on all navigations after the initial page load. The initial page view is sent in the code that sets up GA, therefore we need to use `listenBefore` to track subsequent views, as tracking in `listen` would lead to a duplicate page view being tracked on page load.

I does not seem like a solution to move the initial tracking out from the GA setup code, as that could lead to scenarios where `history.listen` would run before the tracker is set up.

I see no mention of `listenBefore` being removed in any release notes, readmes, etc. Is this API change documented somewhere? What is the suggested alternative?

**Comment by mjackson** [comment]
The use case for `history.listenBefore` was to block changes to the URL. Essentially, you would `return false` or a prompt message from your `listenBefore` hook which would let you block the transition.

The API in v4 for this is `history.block()`. You can see how it's to be used in [this test case](https://github.com/mjackson/history/blob/master/modules/__tests__/TestSequences/BlockEverything.js).

> The initial page view is sent in the code that sets up GA, therefore we need to use listenBefore to track subsequent views, as tracking in listen would lead to a duplicate page view being tracked on page load.

v4 no longer calls the `listen` callback immediately when it is registered. Instead, you can get the current location using `history.location` on the initial page load and any subsequent change using `history.listen`.

**Comment by fredva** [comment]
Thanks for the clarification!

**Comment by chrisege** [comment]
@mjackson was `listenBefore` removed in v3 or v4? I'd be happy to submit a PR making a note of it in the changelog if you can point me to the proper place to put that note. 

(we just ran into the same issue when attempting to upgrade from v2 as well)
