### ISSUE TITLE
Initial State

### ISSUE THREAD

**Issue by jooj123** [mjackson/history#380]
This is probably more of a question than an issue.

I have a SPA application which is initially server side rendered (isomorphic).
On the first SSR I want to add state so that if a user goes back to this initial server side rendered URL the SPA knows how to fetch the data based on the state of history. 

What is the best practice to handle initial state with this package? 
Do I have do just do something like:
```javascript
import createHistory from 'history/createBrowserHistory';

....

history = createHistory();
history.replace({
  pathname: currentUrl,
  search: '?stuff=abc',
  state,
});
```

Or is there a cleaner way of doing this ? It seems a bit hacky that a replace is being called to replace a pathname / search when the path /search hasnt changed.
Is there a nice way of adding this state when doing the `createHistory` call - can it be passed in somehow ?

**Comment by mjackson** [comment]
Yes, if you want `location.state` on the initial page load you have to do a `replace` immediately to get it. However, you don't have to pass along the current `pathname` and `search`. Just use `history.replace({ state })` and you should be fine.

**Comment by jooj123** [comment]
thanks @mjackson 👍

**Comment by jooj123** [comment]
actually this doesnt work, if you have a server side rendered url thats `http://mrdomain/stuff/?other=123` will be replaced with `http://mrdomain/stuff/`

**Comment by mjackson** [comment]
Hmm, in that case you probably need `history.replace({ state, ...window.location })` so you get `pathname` and `search` from the current `window.location` as well.

Going forward, I think it might be interesting to re-use properties from the current location in `push` and `replace` if they're not present in the given argument, but we have to explore all the edge cases first.
