### ISSUE TITLE
How can i get :params from location?

### ISSUE THREAD

**Issue by optimatex** [mjackson/history#391]
I would like to implement wide spread pattern `mywebsite/en/welcome`. In this case i have to modify all my <Link /> for including actual param `:lang` into their prop 'to'. Without this implementation i couldn't know current language. So, i use handleLocationChange to spread curent :lang to all my components. But i receive location prop which include only current path and query. How can i receive curent :lang param too ? 
p.s. i would like to avoid all of this but AFAIK react-router doesn't support relative links

**Comment by mjackson** [comment]
This library doesn't parse `location.pathname` for you, so that needs to happen at some higher level. Also, RR v4 does, in fact, support relative links.

**Comment by optimatex** [comment]
thanks
