### ISSUE TITLE
What is 'Initial POP'?

### ISSUE THREAD

**Issue by MaximVanyushkin** [mjackson/history#392]
In CHANGES.MD for 3rd version I'm found this:

- **Breakage:** `location.key` on the initial POP is `null`. Users who relied on
  this key may immediately use `replace` to get it back

What is 'initial POP'? 
When I'm trying navigate to some route, I'm have got in a middleware 2 sequential actions with the same type (LocationChange). The first action is 'LocationChange:Push', the second action is 'LocationChange:POP'. Also, the second action has 'Key' property assigned to null. 
Which real purpose POP, after PUSH during changing route?

**Comment by mjackson** [comment]
The "initial POP" is the initial location, which is always a `POP`.

```js
const history = createHistory()

history.action // POP
```
