### ISSUE TITLE
window.sessionStorage cannot be used if cookies are disabled

### ISSUE THREAD

**Issue by andi5** [mjackson/history#397]
Similar to #215, but the try-catch-blocks added there does not cover all the cases.

Reproduction:
- use google Chrome (v55.0.2883.87 atm)
- block cookies for all websites
- visit any page that uses DOMStateStorage.(read|save)State from history v3.2.1

`=> Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.`

`"sessionStorage" in window` would simply return `true`, whereas using `window.sessionStorage` throws the exception from above. The code does so without try-catch.

**Comment by mjackson** [comment]
`window.sessionStorage` is unreliable enough that we've ditched it entirely in history 4.x. If you'd like to provide a patch for 3.x I'd be happy to cut a maintenance release, but there will probably eventually be more cases we have yet to uncover. Please upgrade to 4.x if possible.

**Comment by andi5** [comment]
I created https://github.com/andi5/history/tree/session-storage-not-available , but I do not know how to create a pull request against a not-yet-existing v3.x branch.

**Comment by andi5** [comment]
Created #401 instead now.
