### ISSUE TITLE
npm test isn't working

### ISSUE THREAD

**Issue by vjeux** [mjackson/history#399]
I just cloned the repo, `npm install` and `npm test`. Any idea what's going on?

![image](https://cloud.githubusercontent.com/assets/197597/21378581/438f6010-c73f-11e6-9e0d-608d567f687c.png)

**Comment by mjackson** [comment]
Hmm, I cannot reproduce locally. I think it may have to do with an old version of `babel-core` on your machine (see e.g. [this issue](https://github.com/visionmedia/debug/issues/389)). I updated our babel dep on master. Try pulling the latest and starting with a fresh `node_modules`.

**Comment by vjeux** [comment]
Perfect, it's working! Thanks
