### ISSUE TITLE
Correct behavior of basename?

### ISSUE THREAD

**Issue by mindjuice** [mjackson/history#404]
I'm using `createBrowserHistory` directly without `react-router`, and I tried setting the `basename` property.  This worked, and prefixed the URLs I pushed with the right path.

However, I was expecting that `history` would also remove the prefix when handing back the current location to me.

Am I using this feature incorrectly or is there some reason for the asymmetry in `basename` handling?

Thanks!

**Comment by mjackson** [comment]
We currently do [remove the basename prefix](https://github.com/mjackson/history/blob/5f634597fc1a252eac5edca23cae4823a6e591be/modules/createBrowserHistory.js#L54-L57) before giving you location objects, so yes, that is the intent. However, there aren't great tests around this, so there may be a bug.

Can you please provide some sample code? Or even better, a failing test case?

**Comment by mindjuice** [comment]
Thanks for the pointer to the code.  Turns out that it's because I was passing `somepath` instead of `/somepath`.  Not sure if you want to consider that a bug.  We could either "fix" paths that don't start with a `/` or perhaps issue a console warning?  I can put together a PR for either option or just leave it if you prefer.

**Comment by mjackson** [comment]
Hmmm, ya we should probably automatically add a `/` to the front of the basename if users don't have one. I'd be happy for a PR that does this :)
