### ISSUE TITLE
v3 maintenance branch

### ISSUE THREAD

**Issue by fhelwanger** [mjackson/history#412]
Hi,

I was using `react-router` v3 and had an issue regarding `basename` being case sensitive while routes are case insensitive.

The code that makes it case sensitive is here: https://github.com/mjackson/history/blob/6a92da86cdd1e3311a1fb1e8f9598a1f718820db/modules/useBasename.js#L14

I'd happily make a PR to add an option or change it do be case insensitive if you think it's fine, but I can't see a branch where to commit it to. Therefore, I'm opening this issue to know what's the strategy regarding maintaining a v3 branch.

`react-router` v3 depends on it and `history` is such an important dependency to it. I think a maintenance branch would be nice (v2 already has one).

**Comment by timdorr** [comment]
Sure thing. Here you go: https://github.com/mjackson/history/tree/v3.x
