### ISSUE TITLE
QuotaExceededError: Failed to execute 'setItem' on 'Storage'

### ISSUE THREAD

**Issue by VictorienTardif** [mjackson/history#84]
I'm getting an error `QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of '@@History/...' exceeded the quota.` after having loaded many pages.

Am I doing something wrong or is it a bug?

**Comment by mjackson** [comment]
I think it's clear from this issue and from #42 that we need a higher level API that helps us manage interfacing with `sessionStorage` more gracefully than what we have now. Maybe we could keep track of old location keys and expel them if we see this error...

**Comment by VictorienTardif** [comment]
Is there something I can do in the meantime? Or not at all?
Thank you!

**Comment by taion** [comment]
I think the right thing to do is to update the check to the one recommended by MDN: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#Testing_for_support_vs_availability

I'm not aware of any packages that encapsulate this for `sessionStorage` the way `store` does for `localStorage`.

**Comment by mjackson** [comment]
This issue isn't a question of availability, @taion. We discussed that in #42. This is an actual question of exceeding the available quota in `sessionStorage`. Sorry if I misunderstood you.

**Comment by taion** [comment]
Oh, I see - never mind, my bad.

**Comment by colindresj** [comment]
Running into this quite a bit, so wanted to add a note here to see if there's been more discussion on the right implementation for this

**Comment by ryanflorence** [comment]
I built a thing a long time ago in coffeescript (heh) that, when the limit was reached, it started pulling out the oldest stuff in there until there was enough room:

https://github.com/ryanflorence/fifo/blob/master/fifo.coffee

Could do something like that.

Also, what are people putting on state? Seems crazy they've got 5 megs! Seems like it's being abused a bit?

**Comment by taion** [comment]
@ryanflorence We took a stab at this on https://github.com/rackt/history/pull/104, but it wasn't quite enough. We need to persist in session storage the list of keys to fix both that and https://github.com/rackt/history/issues/157.

**Comment by rpedela** [comment]
I am having the same problem. What happens if the oldest entries are removed, and the user clicks the back button enough times? Will the state just be null or will it skip that history entry and go to the next one?

**Comment by colindresj** [comment]
Agree with @ryanflorence — we've abused the quota, so the exception is legitimate. The way we're fixing this, is by updating our code to be more sensible with what gets persisted throughout the browser session.

With that said, however, the react-router API makes it quite easy to run into that abuse. Having a safety net in place seems important in order to ensure confidence in that ease. Us, as developers, have to be careful about how and  what we do, but if history can help out when we're too inattentive to notice, then that's fantastic.

**Comment by mjackson** [comment]
v4 doesn't use session storage *at all* so this issue won't be relevant very soon.

**Comment by EloB** [comment]
I've also has this problem and I'm using react router 3 and cannot update to the latest version because of multiple reasons. Is there any solution to this?

**Comment by morphers82** [comment]
just ran accross this issue as well.

**Comment by chux0519** [comment]
the same error today

**Comment by caphun** [comment]
@mjackson Is there a solution for those stuck on v3?

**Comment by EloB** [comment]
Is there a way to use latest history with old react-router? I can't upgrade to latest react-router because of the context update done in that library.
